from __future__ import annotations
from .model import ProcessorSpec, ResourceEstimate
from .registry import ProcessorRegistry

def _p(
    id, kind, description, *,
    inputs=("ProofObligation",), outputs=("ProcessorArtifact",),
    handles=(), capabilities=(), proofs=(), deterministic=False,
    consequence_free=True, estimate=None, fallback=None, mutation_axes=(),
    evaluator=None,
):
    return ProcessorSpec(
        id=id, version="1", kind=kind, description=description,
        input_types=tuple(inputs), output_types=tuple(outputs),
        handles=tuple(handles), capabilities=tuple(capabilities),
        proof_outputs=tuple(proofs), deterministic=deterministic,
        consequence_free=consequence_free,
        default_estimate=estimate or ResourceEstimate(),
        fallback_pack=fallback,
        mutation_axes=tuple(mutation_axes),
        evaluator_contract=evaluator,
        implementation_hash="stdlib-ref-v1",
    )

STDLIB = [
    _p(
        "problem.decompose","DECOMPOSE",
        "Lower one unresolved proof obligation into smaller typed sub-obligations without changing its acceptance semantics.",
        handles=("unknown","broad_spec","compound","stuck"),
        outputs=("SubProofGraph",), deterministic=False,
        estimate=ResourceEstimate(wall_seconds=20,input_tokens=8000,output_tokens=2500),
        fallback="proof.stuck",
        mutation_axes=("decomposition_depth","ordering","model"),
    ),
    _p(
        "history.retrieve","RETRIEVE",
        "Retrieve similar previously verified runs, best-known processor graphs, failures and reusable artifacts.",
        handles=("unknown","build","test","deploy","payment","stuck","optimize"),
        outputs=("HistoricalFoundationSet",), deterministic=True,
        estimate=ResourceEstimate(wall_seconds=1),
        mutation_axes=("similarity_threshold","top_k"),
    ),
    _p(
        "reuse.search","SEARCH",
        "Search local repos/packages/verified artifacts for an admissible component before building.",
        handles=("build","integration","code","stuck"),
        capabilities=("repository.read","package.index"),
        outputs=("ReuseCandidates",),
        estimate=ResourceEstimate(wall_seconds=15,input_tokens=3000,output_tokens=1000),
        fallback="proof.stuck",
        mutation_axes=("search_depth","source_order"),
    ),
    _p(
        "web.search","SEARCH",
        "Search current external sources for evidence, APIs, components or problem-solving information.",
        handles=("unknown","research","stuck","external","tool_gap"),
        capabilities=("web.search",),
        outputs=("SearchEvidence",),
        estimate=ResourceEstimate(wall_seconds=30,input_tokens=6000,output_tokens=2000),
        fallback="proof.stuck",
        mutation_axes=("query_strategy","depth","domains"),
    ),
    _p(
        "data.discover","DISCOVER",
        "Discover datasets/APIs/sensors that can materially improve resolution of an unresolved proof obligation.",
        handles=("unknown","research","data_gap","stuck"),
        capabilities=("web.search","data.catalog"),
        outputs=("DataCandidates",),
        estimate=ResourceEstimate(wall_seconds=40,input_tokens=7000,output_tokens=2000),
        fallback="proof.stuck",
        mutation_axes=("catalogs","voi_threshold"),
    ),
    _p(
        "tool.discover","DISCOVER",
        "Find a tool, plugin, MCP, package or service capable of a missing operation.",
        handles=("tool_gap","capability_gap","stuck"),
        capabilities=("tool.catalog",),
        outputs=("ToolCandidates",),
        estimate=ResourceEstimate(wall_seconds=20,input_tokens=4000,output_tokens=1000),
        fallback="proof.stuck",
        mutation_axes=("catalogs","cost_weight"),
    ),
    _p(
        "config.apply","BUILD",
        "Apply the minimum configuration delta required by a proof obligation.",
        handles=("configure","configuration","integration"),
        capabilities=("filesystem.write",),
        outputs=("ConfigArtifact",),
        estimate=ResourceEstimate(wall_seconds=90,input_tokens=12000,output_tokens=2500),
        fallback="implementation.failing",
        mutation_axes=("config_route","model"),
    ),
    _p(
        "integration.compose","BUILD",
        "Compose/reuse existing components at an integration boundary without redesigning them.",
        handles=("integration","reuse","code"),
        capabilities=("filesystem.write","shell"),
        outputs=("IntegrationArtifact","IntegrationTestPlan"),
        estimate=ResourceEstimate(wall_seconds=180,input_tokens=25000,output_tokens=6000),
        fallback="implementation.failing",
        mutation_axes=("adapter_shape","model","dependency_choice"),
    ),
    _p(
        "code.build","BUILD",
        "Implement the minimum missing code delta required to make a bound proof leaf provable.",
        handles=("build","code","implementation"),
        capabilities=("filesystem.write","shell"),
        outputs=("CodeArtifact","TestPlan"),
        estimate=ResourceEstimate(wall_seconds=300,input_tokens=50000,output_tokens=12000),
        fallback="implementation.failing",
        mutation_axes=("model","reasoning_effort","patch_strategy"),
    ),
    _p(
        "code.test","TEST",
        "Run deterministic tests and return observations/artifacts, never a self-authored canonical verdict.",
        handles=("test","code","implementation","validation"),
        capabilities=("shell",),
        outputs=("TestEvidence",),
        deterministic=True,
        estimate=ResourceEstimate(wall_seconds=60),
        mutation_axes=("test_order","coverage_subset"),
    ),
    _p(
        "probe.design","PROBE",
        "Design the cheapest direct observation capable of resolving or falsifying a claim.",
        handles=("unknown","measurement","external","stuck"),
        outputs=("ProbeSpecCandidate",),
        estimate=ResourceEstimate(wall_seconds=20,input_tokens=5000,output_tokens=1500),
        fallback="proof.stuck",
        mutation_axes=("probe_route","independence","freshness"),
    ),
    _p(
        "redteam.falsify","RED_TEAM",
        "Search specifically for counterexamples and false-PASS paths against the frozen evaluator.",
        handles=("security","validation","stuck","promotion"),
        outputs=("CounterexampleSet",),
        estimate=ResourceEstimate(wall_seconds=90,input_tokens=18000,output_tokens=5000),
        fallback="implementation.failing",
        mutation_axes=("attack_family","adversary_model","seed"),
    ),
    _p(
        "failure.classify","COMPARE",
        "Classify failure evidence into implementation, environment, authority, evidence-route or contract ambiguity.",
        handles=("failure","stuck"),
        outputs=("FailureClass",),
        deterministic=False,
        estimate=ResourceEstimate(wall_seconds=10,input_tokens=3000,output_tokens=800),
        mutation_axes=("classifier","taxonomy_version"),
    ),
    _p(
        "repair.propose","REPAIR",
        "Generate the minimum repair candidates for a classified failure while preserving evaluator identity.",
        handles=("failure","repair","stuck"),
        outputs=("RepairCandidates",),
        estimate=ResourceEstimate(wall_seconds=40,input_tokens=12000,output_tokens=3000),
        fallback="implementation.failing",
        mutation_axes=("repair_style","model","context"),
    ),
    _p(
        "replace.component","REPAIR",
        "Search and substitute a failing dependency/component rather than endlessly patching it.",
        handles=("dependency_failure","repair","stuck"),
        capabilities=("repository.read","package.index"),
        outputs=("ReplacementCandidates",),
        estimate=ResourceEstimate(wall_seconds=45,input_tokens=8000,output_tokens=2000),
        mutation_axes=("ecosystem","compatibility_weight"),
    ),
    _p(
        "cg.simulate","SIMULATE",
        "Run a candidate processor/policy in one or more replayable CG worlds before spending on reality.",
        handles=("simulation","uncertainty","stuck","promotion"),
        capabilities=("cg.run",),
        outputs=("CGRunReceipt",),
        deterministic=True,
        estimate=ResourceEstimate(wall_seconds=120),
        mutation_axes=("world","seed","scenario"),
        evaluator="cg/world-evaluator",
    ),
    _p(
        "cg.replay","SIMULATE",
        "Replay a verified historical run under mutated processor policies in frozen worlds.",
        handles=("optimize","historical","promotion"),
        capabilities=("cg.run",),
        outputs=("ReplayRunSet",),
        deterministic=True,
        estimate=ResourceEstimate(wall_seconds=180),
        mutation_axes=("model","tool_order","processor_graph","budget","context"),
        evaluator="cg/world-evaluator",
    ),
    _p(
        "cg.compare","COMPARE",
        "Lexicographically compare control and candidate runs under the same world/evaluator.",
        handles=("compare","promotion","optimize"),
        capabilities=("cg.compare",),
        outputs=("ComparisonEvidence",),
        deterministic=True,
        estimate=ResourceEstimate(wall_seconds=10),
        evaluator="cg/world-evaluator",
    ),
    _p(
        "world.generate","WORLD_GENERATE",
        "Generate or curate a replayable adversarial world for a processor/proof family.",
        handles=("world_gap","counterexample","benchmark"),
        capabilities=("mwgym.world","cg.world"),
        outputs=("WorldPackCandidate",),
        estimate=ResourceEstimate(wall_seconds=120,input_tokens=20000,output_tokens=6000),
        mutation_axes=("domain","difficulty","hidden_state","tool_costs"),
    ),
    _p(
        "trajectory.analyse","OPTIMIZE",
        "Analyse verified trajectories for repeated waste, blockers, successful routes and candidate policy improvements.",
        handles=("optimize","historical"),
        outputs=("TrajectoryAnalysis",),
        estimate=ResourceEstimate(wall_seconds=30,input_tokens=10000,output_tokens=2500),
        mutation_axes=("objective","window","cluster"),
    ),
    _p(
        "seed0.mutate","MUTATE",
        "Generate bounded candidate execution policies/processor graphs for tournament evaluation.",
        handles=("optimize","promotion","historical"),
        outputs=("PolicyCandidates",),
        estimate=ResourceEstimate(wall_seconds=30,input_tokens=10000,output_tokens=3000),
        mutation_axes=("processor_graph","model","budget","order","reasoning","tools"),
    ),
    _p(
        "seed0.tournament","COMPARE",
        "Run multiple candidates against one frozen ContractRoot and hard evaluator; emit ranking evidence only.",
        handles=("promotion","optimize","variant"),
        capabilities=("seed0.tournament",),
        outputs=("TournamentReceipt",),
        deterministic=True,
        estimate=ResourceEstimate(wall_seconds=240),
        evaluator="seed0/frozen-evaluator",
    ),
    _p(
        "policy.promote.propose","OPTIMIZE",
        "Produce a promotion proposal from comparison evidence. Does not perform the QP promotion itself.",
        handles=("promotion",),
        outputs=("PromotionProposal",),
        deterministic=True,
        consequence_free=True,
        estimate=ResourceEstimate(wall_seconds=2),
        evaluator="qp/promotion-gate",
    ),
    _p(
        "block.resolve","ESCALATE",
        "Mechanically classify a proven blocker as continue/replan/H/M/fail; cannot mint authority itself.",
        handles=("blocker","capability_gap","authority_gap"),
        outputs=("BlockResolution",),
        deterministic=True,
        estimate=ResourceEstimate(wall_seconds=1),
    ),
]

def install_stdlib(registry: ProcessorRegistry) -> ProcessorRegistry:
    for spec in STDLIB:
        registry.register(spec)
    return registry
